# Generated by Django 6.0 on 2025-12-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre público que verán los votantes (puede diferir del nombre de usuario).', max_length=255, verbose_name='nombre en boleta')),
                ('bio', models.TextField(blank=True, verbose_name='biografía/propuesta')),
                ('image', models.URLField(blank=True, help_text='Enlace a la imagen del candidato, alojada externamente.', max_length=500, null=True, verbose_name='URL de imagen/avatar')),
            ],
            options={
                'verbose_name': 'candidato',
                'verbose_name_plural': 'candidatos',
                'ordering': ['name'],
            },
        ),
    ]
