"""
Django settings for validvote project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta # Importado para Simple JWT

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment-checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-5-2_&1v!0+*j62$mj7d!q6#^$$l)(+vmi(w!06_$j0vr_1j((k'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # ----------------------------------
    # CONFIGURACIÓN DE APPS DE TERCEROS
    # ----------------------------------
    'rest_framework',         # Necesario para el API REST
    'corsheaders',            # Necesario para permitir llamadas desde el frontend (Vite)
    'rest_framework_simplejwt', # Necesario para la autenticación JWT
    
    # ----------------------------------
    # CONFIGURACIÓN DE APPS LOCALES
    # ----------------------------------
    'apps.core',              # App base
    'apps.users',             # App de Usuarios (incluye el modelo de usuario personalizado)
    'apps.elections',         # App de Elecciones
    'apps.candidates',        # App de Candidatos
    'apps.voter',             # App de Padrón Electoral
    'apps.votes',             # App de Votos
    'apps.mockchain',         # App de Mockchain (simulación)
    'apps.results',           # App de Resultados (asumimos que existe)
    'apps.mockextusers',      # App de Mock de API Externa (simulación)
]

MIDDLEWARE = [
    # CORS HEADERS debe ir tan arriba como sea posible, antes de CommonMiddleware
    'corsheaders.middleware.CorsMiddleware', # <-- CAMBIO: Añadido para CORS
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'validvote.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'validvote.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# ----------------------------------------------------
## CONFIGURACIÓN DE USUARIO PERSONALIZADO (Proceso P0)
# ----------------------------------------------------
AUTH_USER_MODEL = 'users.User' # <-- CAMBIO: Establece el modelo de usuario personalizado

# ----------------------------------------------------
## CONFIGURACIÓN DJANGO REST FRAMEWORK (DRF)
# ----------------------------------------------------
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # Utilizamos JWT como método de autenticación por defecto
        'rest_framework_simplejwt.authentication.JWTAuthentication', # <-- CAMBIO: Añadido
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        # Requerimos que el usuario esté autenticado para casi todas las rutas
        'rest_framework.permissions.IsAuthenticated', # <-- CAMBIO: Añadido
    ),
    'NON_FIELD_ERRORS_KEY': 'error', # Nombra la clave de errores no relacionados con campos
}

# ----------------------------------------------------
## CONFIGURACIÓN SIMPLE JWT
# ----------------------------------------------------
SIMPLE_JWT = {
    # Tiempo de vida del token de acceso (corto, usado para peticiones)
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60), # <-- CAMBIO: 60 minutos
    # Tiempo de vida del token de refresco (largo, usado para obtener nuevos tokens de acceso)
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1), # <-- CAMBIO: 1 día
    # Utiliza la cookie http-only para el token de refresco (opcional, pero buena práctica)
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'JTI_CLAIM': 'jti',
}

# ----------------------------------------------------
## CONFIGURACIÓN CORS HEADERS (VITE/REACT)
# ----------------------------------------------------

# Permitir credenciales (cookies, encabezados de autenticación)
CORS_ALLOW_CREDENTIALS = True # <-- CAMBIO: Necesario para enviar credenciales

# El frontend de Vite/React se ejecuta típicamente en http://localhost:5173
# Se debe incluir el puerto específico de desarrollo de Vite
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173", # <-- CAMBIO: Origen de desarrollo típico de Vite/React
    "http://127.0.0.1:5173", # <-- CAMBIO: Origen alternativo de desarrollo
]

# También se puede usar CORS_ALLOW_ALL_ORIGINS = DEBUG (si DEBUG es True)
# Pero es mejor ser explícito.