# Generated by Django 6.0 on 2025-12-09 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(help_text='Hash criptográfico del contenido del voto (publicado en blockchain).', max_length=64, unique=True, verbose_name='hash del voto (vote_hash)')),
                ('tx_id', models.CharField(help_text='Identificador de la transacción en la blockchain (hash de la transacción).', max_length=255, unique=True, verbose_name='ID de transacción')),
                ('published_at', models.DateTimeField(help_text='Fecha en la que la transacción fue confirmada y registrada en la blockchain.', verbose_name='fecha de publicación en blockchain')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_records', to='elections.election', verbose_name='elección')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='votes_cast', to=settings.AUTH_USER_MODEL, verbose_name='usuario votante')),
            ],
            options={
                'verbose_name': 'registro de voto',
                'verbose_name_plural': 'registros de votos',
                'ordering': ['-published_at'],
                'unique_together': {('election', 'user')},
            },
        ),
    ]
