# Generated by Django 6.0 on 2025-12-09 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed', models.BooleanField(default=False, help_text='Indica si el administrador ha autorizado a este usuario para votar en la elección.', verbose_name='habilitado para votar')),
                ('voted', models.BooleanField(default=False, help_text='Indica si el usuario ya emitió su voto. Si es True, bloquea nuevos intentos.', verbose_name='voto emitido')),
                ('ext_verified', models.BooleanField(default=False, help_text='Indica si la habilitación (allowed) proviene de un sistema de padrón oficial o externo.', verbose_name='verificado externamente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voters_register', to='elections.election', verbose_name='elección')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voter_permissions', to=settings.AUTH_USER_MODEL, verbose_name='usuario votante')),
            ],
            options={
                'verbose_name': 'votante habilitado',
                'verbose_name_plural': 'votantes habilitados',
                'ordering': ['user__email'],
                'unique_together': {('election', 'user')},
            },
        ),
    ]
