# Generated by Django 6.0 on 2025-12-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('desc', models.TextField(blank=True, verbose_name='descripción')),
                ('start_at', models.DateTimeField(verbose_name='fecha de inicio')),
                ('end_at', models.DateTimeField(verbose_name='fecha de fin')),
                ('type', models.CharField(choices=[('PUBLIC', 'Pública'), ('PRIVATE', 'Privada'), ('INTERNAL', 'Interna / Institucional')], default='PRIVATE', max_length=20, verbose_name='tipo')),
                ('max_sel', models.PositiveIntegerField(default=1, help_text='Número máximo de candidatos que se pueden seleccionar en un solo voto.', verbose_name='selecciones máximas')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('OPEN', 'Abierta'), ('CLOSED', 'Finalizada'), ('ARCHIVED', 'Archivada')], default='DRAFT', max_length=10, verbose_name='estado')),
                ('ext_validation_url', models.URLField(blank=True, help_text='URL del servicio que valida la elegibilidad del votante si no está en el padrón local.', max_length=500, null=True, verbose_name='URL de Validación Externa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'elección',
                'verbose_name_plural': 'elecciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
