# Generated by Django 6.0 on 2025-12-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MockchainTx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_id', models.CharField(help_text='Identificador único que simula el hash de la transacción en la red.', max_length=255, unique=True, verbose_name='ID de transacción simulada')),
                ('payload_hash', models.CharField(help_text='Hash del contenido del voto, utilizado para verificación externa.', max_length=64, unique=True, verbose_name='hash de la carga útil')),
                ('payload', models.JSONField(help_text='Contenido JSON estructurado y firmado del voto (simulación de datos on-chain).', verbose_name='carga útil del voto')),
                ('block_number', models.PositiveIntegerField(default=0, help_text='Número de bloque simulado en el que se "minó" la transacción.', verbose_name='número de bloque')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'transacción mockchain',
                'verbose_name_plural': 'transacciones mockchain',
                'ordering': ['-created_at'],
            },
        ),
    ]
