# Generated by Django 6.0 on 2025-12-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('full_name', models.CharField(max_length=255, verbose_name='full name')),
                ('role', models.CharField(choices=[('STUDENT', 'Estudiante'), ('PROFESSOR', 'Profesor'), ('EXECUTIVE', 'Ejecutivo')], default='STUDENT', max_length=20, verbose_name='rol')),
                ('student_class', models.CharField(blank=True, max_length=100, null=True, verbose_name='clase/sección')),
                ('school_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='año escolar')),
                ('subjects_taught', models.JSONField(blank=True, default=list, help_text='Lista de asignaturas que imparte.', verbose_name='asignaturas')),
                ('degree', models.CharField(blank=True, choices=[('Bachelor', 'Licenciatura'), ('Master', 'Maestría'), ('Doctor', 'Doctorado')], max_length=50, null=True, verbose_name='grado académico')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'usuario de prueba',
                'verbose_name_plural': 'usuarios de prueba',
                'ordering': ['email'],
            },
        ),
    ]
